data:
  # path: 'mgr_data/MS1M_small'
  path: 'mgr_data/CasiaWebFace_small'
  # path: 'mgr_data/LFW'
  # path: 'mgr_data/data_sample'
  test_data: 'mgr_data/MS1M_small'
  test_embeddings: 'mgr_data/embeddings/adaface_LFW_embeddings.csv'
  # test_embeddings: 'mgr_data/embeddings/adaface_data_sample_embeddings.csv'
model:
  embeddings: adaface 
  quality_model: facenet
